- name: Create docker-compose.yml file
  file:
    name: "{{ compose_project_dir }}/docker-compose.yml"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    state: touch

- name: deploy Docker Compose wordpress project
  template:
    src: "{{ compose_project_dir }}/roles/wordpress/template/docker-compose.j2"
    dest: "{{compose_project_dir}}/docker-compose.yml"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0644
  tags:
    - deploy_compose

- name: deploy Nginx virtual host
  template:
    src: "{{ compose_project_dir }}/roles/wordpress/template/wordpress-nginx.j2"
    dest: "{{ compose_project_dir }}/nginx/wordpress-nginx.conf"
    owner: "{{ system_user }}"
    group: "{{ system_user }}"
    mode: 0644
  tags:
    - gen_nginx

- name: docker-compose up
  command: docker-compose -f docker-compose.yml up -d
  args:
    chdir: "{{ compose_project_dir }}"
